# Generated by Django 4.1.3 on 2022-11-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_news', models.CharField(max_length=255, verbose_name='Название сайта.')),
                ('image_news', models.ImageField(upload_to='news_image/', verbose_name='Фотография нововсти.')),
                ('description_news', models.TextField(verbose_name='Описание новости.')),
                ('created_news', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
