# Generated by Django 4.1.3 on 2022-11-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('massage', models.TextField(verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Коментрарии',
                'verbose_name_plural': 'Коментарий',
            },
        ),
    ]
