# Generated by Django 4.1.3 on 2022-11-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_about_1', models.CharField(max_length=123, verbose_name='Выгоды - 1')),
                ('name_desc_1', models.TextField(verbose_name='Описание про <<Выгоды - 1>>')),
                ('name_about_2', models.CharField(max_length=223, verbose_name='Выгоды - 2')),
                ('name_desc_2', models.TextField(verbose_name='Описание про <<Выгоды - 2>>')),
                ('name_about_3', models.CharField(max_length=333, verbose_name='Выгоды - 3')),
                ('name_desc_3', models.TextField(verbose_name='Описание про <<Выгоды - 3>>')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
