# Generated by Django 4.1.3 on 2022-11-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Телефонный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=1, upload_to='profile_image/', verbose_name='Фотография профиля'),
            preserve_default=False,
        ),
    ]
