# Generated by Django 4.1.3 on 2022-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='profile_image/', verbose_name='Фотография профиля'),
            preserve_default=False,
        ),
    ]
