# Generated by Django 4.1.3 on 2022-11-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('desc', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='logo_site/', verbose_name='Логотип сайта ')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройка',
            },
        ),
    ]
