# Generated by Django 4.1.3 on 2022-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=244, verbose_name='Название игры')),
                ('desc_game', models.TextField(max_length=255, verbose_name='Описание игры')),
                ('url_game', models.URLField(verbose_name='Ссылка на игру')),
                ('image_game', models.ImageField(upload_to='GamePhto/', verbose_name='Фотография игры ')),
            ],
            options={
                'verbose_name': 'Игры',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
