# Generated by Django 4.1.3 on 2022-11-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, verbose_name='Вопрос!')),
                ('desc', models.TextField(verbose_name='Ответ!')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы!',
                'verbose_name_plural': 'Часто задаваемые вопросы!',
            },
        ),
    ]
