# Generated by Django 4.1.3 on 2022-11-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team', models.CharField(max_length=24, verbose_name='Имя')),
                ('image_team', models.ImageField(upload_to='team_image/', verbose_name=' Фотография')),
                ('work_team', models.CharField(max_length=244, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Наша команда!',
                'verbose_name_plural': 'Наша команда!',
            },
        ),
    ]
